### PR TITLE
Fix CurExp Save

### PR DESCRIPTION
**Pull request by Kadaz**

### CODE REVIEW

**Comment by Zindel-Pam** [comment]
thanks for your effort, you are in the discord group?

**Comment by Kadaz** [comment]
Nope. Can you send me a link to enter?

**Comment by Zindel-Pam** [comment]
https://discord.gg/hwrt6Cz

**Comment by Kadaz** [comment]
I'm Solidus84.

**Review by ivanlamega — APPROVED** [review]

**Pull request merged**
